export const CONTINENTS_LIST_REQUEST = 'CONTINENTS_LIST_REQUEST';
export const CONTINENTS_LIST_SUCCESS = 'CONTINENTS_LIST_SUCCESS';
export const CONTINENTS_LIST_FAIL = 'CONTINENTS_LIST_FAIL';

export const CONTINENTS_DATES_REQUEST = 'CONTINENTS_DATES_REQUEST';
export const CONTINENTS_DATES_SUCCESS = 'CONTINENTS_DATES_SUCCESS';
