export const COUNTRIES_LIST_REQUEST = 'COUNTRIES_LIST_REQUEST';
export const COUNTRIES_LIST_SUCCESS = 'COUNTRIES_LIST_SUCCESS';
export const COUNTRIES_LIST_FAIL = 'COUNTRIES_LIST_FAIL';

export const COUNTRIES_DATES_REQUEST = 'COUNTRIES_DATES_REQUEST';
export const COUNTRIES_DATES_SUCCESS = 'COUNTRIES_DATES_SUCCESS';

// export const COUNTRIES_DATES_REQUEST
