export const STATES_LIST_REQUEST = 'STATES_LIST_REQUEST';
export const STATES_LIST_SUCCESS = 'STATES_LIST_SUCCESS';
export const STATES_LIST_FAIL = 'STATES_LIST_FAIL';

export const STATES_DATES_REQUEST = 'STATES_DATES_REQUEST';
export const STATES_DATES_SUCCESS = 'STATES_DATES_SUCCESS';

// export const COUNTRIES_DATES_REQUEST
